version: '3'
services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
    - ./client/docker/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
    - "9090:9090"
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
    - "3000:3000"

  demo-service:
    container_name: demo-service
    build:
      context: ./demoservice/
    image: demo-service:latest
    ports:
    - 8090:8090
    expose:
      - 8090
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`192.168.2.235`)"
      - "traefik.http.routers.whoami.entrypoints=web"

  traefik:
    image: "traefik:v2.2"
    container_name: "traefik"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--metrics"
      - "--api"
      - "--metrics.prometheus.buckets=0.1,0.3,1.2,5.0"
    ports:
      - "80:80"
      - "8181:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"