{
 "title": "custom CB dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Demo Service CB Closed",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "resilience4j_circuitbreaker_state{name=\"demoService\", state=\"closed\"}"
    }
   ]
  },
  {
   "title": "Demo Service CB Open",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 7, "x": 7, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "resilience4j_circuitbreaker_state{name=\"demoService\", state=\"open\"}"
    }
   ]
  },
  {
   "title": "Demo Service CB Half-Open",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 7, "x": 14, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "resilience4j_circuitbreaker_state{name=\"demoService\", state=\"half_open\"}"
    }
   ]
  },
  {
   "title": "Demo Service Traffic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(traefik_service_requests_total{service=\"demoservice-app@docker\"}[1m]))",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(rate(traefik_service_requests_total{service=\"demoservice-app@docker\"}[1m])) by (code)",
     "legendFormat": "{{ code }}"
    }
   ]
  },
  {
   "title": "Failure Rate Demo Service",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 12, "y": 4 },
   "targets": [
    {
     "expr": "resilience4j_circuitbreaker_failure_rate{name=\"demoService\"}",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "graph",
   "gridPos": { "h": 8, "w": 17, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(resilience4j_circuitbreaker_calls_seconds_count{name=\"demoService\"}[1m])",
     "legendFormat": "{{ kind }} "
    },
    {
     "expr": "rate(resilience4j_circuitbreaker_calls_total{name=\"demoService\"}[1m])",
     "legendFormat": "{{ kind }} "
    }
   ]
  }
 ]
}