version: '3.7'

services:
  client-service:
    image: client-service:latest
    networks:
      - inbound
    ports:
      - 8091:8091
    expose:
      - 8091
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
networks:
  inbound:
   external: true
