server:
  port: 8092

feign:
#  client:
#    url : http://localhost:8099
  hystrix:
    enabled: true

spring:
  application:
    name: spring-cloud-client

#eureka.client.service-url.defaultZone=${EUREKA_URI:http://localhost:8761/eureka}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
#  instance:
#    prefer-ip-address: true


#eureka.client.register-with-eureka=true
#eureka.client.fetch-registry=true